language: go

go:
#  - "1.6"
#  - "1.7"
  - "1.10"
#  - "tip"

env:
  - GOARCH=amd64

sudo: false

matrix:
  include:
    - dist: trusty
    - dist: xenial
    #- dist: artful

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y gtk+3.0 libgtk-3-dev
  - sudo apt-get install -qq -y xvfb
  - "export DISPLAY=:99.0"
  - sudo /usr/bin/Xvfb $DISPLAY 2>1 > /dev/null &
  - "export GTK_VERSION=$(pkg-config --modversion gtk+-3.0 | tr . _| cut -d '_' -f 1-2)"
  - "export GLib_VERSION=$(pkg-config --modversion glib-2.0 | tr . _| cut -d '_' -f 1-2)"
  - "export Cairo_VERSION=$(pkg-config --modversion cairo)"
  - "export Pango_VERSION=$(pkg-config --modversion pango)"
  - echo "GTK version ${GTK_VERSION} (GLib ${GLib_VERSION}, Cairo ${Cairo_VERSION}, Pango ${Pango_VERSION})"

install:
  - go get -t -tags "gtk_${GTK_VERSION} glib_${GLib_VERSION}" github.com/d2r2/gotk3/...

#script:
#  - go test -tags "gtk_${GTK_VERSION} glib_${GLib_VERSION}"
